org: prosingularity
app: fursorger-backend
service: fursorger-backend

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
    - serverless-offline # must come after typescript

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-central-1
    stage: prod # for sls offline, access via localhost:3140/prod/level, for sls deploy access via aws-domain/prod/prod/level
    environment:
        DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
        RUNTIME: ${env:RUNTIME}

functions:
    fursorgerBackend: # The name of the lambda function
        # The module 'handler' is exported in the file 'src/lambda'
        handler: src/lambda.create
        events:
            - http:
                  path: /{any+}
                  method: post
